name: Stats
on:
  # Executado uma vez por dia Ã  01:00 UTC (no Brasil, isso pode ser 22:00 dependendo do fuso).
  schedule: [{cron: "0 1 * * *"}]
  # permite rodar manualmente e a cada commit nas branches main ou master
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    paths-ignore:
      - "profile/**"
      - ".github/workflows/**"
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >
            username=EnricoGollner&show_icons=true&theme=shadow_red&card_width=320&include_all_commits=true&count_private=true
          path: profile/stats.svg
          token: ${{ secrets.STATS_TOKEN }}
    
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: >
            username=EnricoGollner&hide=c%2b%2b,cmake,swift,c&layout=compact&size_weight=0.5&count_weight=0.5&theme=shadow_red&card_width=320
          path: profile/top-langs.svg
          token: ${{ secrets.STATS_TOKEN }}
    
      - name: Commit and push cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "updating stats" || exit 0
          git push
